package capture

import (
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"net"
	"sync/atomic"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"

	"github.com/traffic-agent/traffic-agent/internal/config"
	"github.com/traffic-agent/traffic-agent/internal/types"
)

// TCDropCount tracks how many TC events were dropped because the Go channel
// was full. Read and reset via TCDropCountReset().
var tcDropCount atomic.Uint64

// TCDropCountReset returns the current drop count and resets it to zero.
func TCDropCountReset() uint64 {
	return tcDropCount.Swap(0)
}

// PacketEventSize is the fixed size of the C struct packet_event.
// Must match sizeof(struct packet_event) in bpf/tc_capture.c.
const PacketEventSize = 8 + 4 + 4 + 2 + 2 + 1 + 1 + 1 + 1 + 4 + maxPayloadSize

const maxPayloadSize = 2048

// rawPacketEvent mirrors struct packet_event from tc_capture.c.
// Fields are in native byte order as written by the BPF program.
type rawPacketEvent struct {
	TimestampNS uint64
	SrcIP       uint32
	DstIP       uint32
	SrcPort     uint16
	DstPort     uint16
	Direction   uint8
	Protocol    uint8
	TCPFlags    uint8
	_           uint8 // padding
	PayloadLen  uint32
	Payload     [maxPayloadSize]byte
}

// Capturer attaches TC eBPF programs to a network interface and reads
// packet events from the BPF ring buffer.
type Capturer struct {
	cfg      *config.Config
	objs     TCCaptureObjects // generated by bpf2go
	links    []link.Link
	reader   *ringbuf.Reader
	iface    *net.Interface
}

// New creates a new Capturer. Call Start to attach programs and begin reading.
func New(cfg *config.Config) (*Capturer, error) {
	return &Capturer{cfg: cfg}, nil
}

// Start loads the eBPF programs, attaches TC hooks, and begins reading events
// from the ring buffer. Received events are sent to the provided channel.
// The channel is closed when Stop is called.
//
func (c *Capturer) Start(events chan<- *types.RawPacketEvent) error {
	// Remove kernel memory limits for eBPF (required on kernels < 5.11).
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock rlimit: %w", err)
	}

	// Load pre-compiled eBPF programs (embedded by bpf2go).
	if err := LoadTCCaptureObjects(&c.objs, &ebpf.CollectionOptions{
		Programs: ebpf.ProgramOptions{
			LogLevel: ebpf.LogLevelInstruction,
			LogSize:  1 << 23, // 8 MiB — enough for full verifier output
		},
	}); err != nil {
		return fmt.Errorf("load eBPF objects: %w", err)
	}

	// Look up the target network interface.
	iface, err := net.InterfaceByName(c.cfg.Interface)
	if err != nil {
		return fmt.Errorf("interface %q not found: %w", c.cfg.Interface, err)
	}
	c.iface = iface

	// Attach TC ingress hook.
	if err := c.attachTC(iface, c.objs.TcIngress, "ingress"); err != nil {
		return fmt.Errorf("attach TC ingress on %s: %w", c.cfg.Interface, err)
	}

	// Attach TC egress hook.
	if err := c.attachTC(iface, c.objs.TcEgress, "egress"); err != nil {
		return fmt.Errorf("attach TC egress on %s: %w", c.cfg.Interface, err)
	}

	log.Printf("[capture] TC hooks attached on interface %s", c.cfg.Interface)

	// Open ring buffer reader.
	c.reader, err = ringbuf.NewReader(c.objs.Events)
	if err != nil {
		return fmt.Errorf("open ring buffer: %w", err)
	}

	// Start the reader goroutine.
	go c.readLoop(events)

	return nil
}

// Stop detaches TC programs and closes the ring buffer.
func (c *Capturer) Stop() error {
	if c.reader != nil {
		_ = c.reader.Close()
	}
	for _, l := range c.links {
		_ = l.Close()
	}
	c.objs.Close()
	return nil
}

// BPF filter_config flags.
const (
	filterFlagEnabled = 0x1 // enable IP/port inclusion filter
	filterFlagSkipTLS = 0x2 // skip port 443/8443 (ciphertext; SSL uprobes capture plaintext)
)

// filterConfig mirrors struct filter_config in bpf/tc_capture.c.
type filterConfig struct {
	SrcIP   uint32
	DstIP   uint32
	SrcPort uint16
	DstPort uint16
	Flags   uint32
}

// UpdateFilter writes updated BPF filter config to the filter_config_map.
func (c *Capturer) UpdateFilter(srcIP, dstIP net.IP, srcPort, dstPort uint16) error {
	var cfg filterConfig
	if srcIP != nil {
		cfg.SrcIP = ipToUint32(srcIP)
	}
	if dstIP != nil {
		cfg.DstIP = ipToUint32(dstIP)
	}
	cfg.SrcPort = srcPort
	cfg.DstPort = dstPort
	if cfg.SrcIP != 0 || cfg.DstIP != 0 || cfg.SrcPort != 0 || cfg.DstPort != 0 {
		cfg.Flags = filterFlagEnabled
	}

	key := uint32(0)
	return c.objs.FilterConfigMap.Put(key, cfg)
}

// SetSkipTLS tells the BPF program to skip packets on TLS ports (443, 8443).
// When SSL uprobes capture plaintext, TC-captured ciphertext is useless.
func (c *Capturer) SetSkipTLS(skip bool) error {
	key := uint32(0)
	var cfg filterConfig
	// Read existing config to preserve IP/port filter settings.
	_ = c.objs.FilterConfigMap.Lookup(key, &cfg)
	if skip {
		cfg.Flags |= filterFlagSkipTLS
	} else {
		cfg.Flags &^= filterFlagSkipTLS
	}
	return c.objs.FilterConfigMap.Put(key, cfg)
}

// readLoop reads events from the BPF ring buffer and forwards them to ch.
// This goroutine must remain fast — no /proc I/O or other blocking calls.
func (c *Capturer) readLoop(ch chan<- *types.RawPacketEvent) {
	for {
		record, err := c.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			log.Printf("[capture] ring buffer read error: %v", err)
			continue
		}

		ev, err := parsePacketEvent(record.RawSample)
		if err != nil {
			log.Printf("[capture] parse error: %v", err)
			continue
		}

		select {
		case ch <- ev:
		default:
			// Drop event if consumer is too slow; counted via atomic.
			tcDropCount.Add(1)
		}
	}
}

// parsePacketEvent deserialises a raw ring buffer record into a RawPacketEvent.
func parsePacketEvent(data []byte) (*types.RawPacketEvent, error) {
	if len(data) < int(unsafe.Sizeof(rawPacketEvent{})) {
		return nil, fmt.Errorf("short record: %d bytes", len(data))
	}

	var raw rawPacketEvent
	raw.TimestampNS = binary.LittleEndian.Uint64(data[0:8])
	// IPs are written in network byte order (big-endian) by the BPF program.
	raw.SrcIP = binary.BigEndian.Uint32(data[8:12])
	raw.DstIP = binary.BigEndian.Uint32(data[12:16])
	// Ports are converted to host byte order (little-endian) by bpf_ntohs in the BPF program.
	raw.SrcPort = binary.LittleEndian.Uint16(data[16:18])
	raw.DstPort = binary.LittleEndian.Uint16(data[18:20])
	raw.Direction = data[20]
	raw.Protocol = data[21]
	raw.TCPFlags = data[22]
	// data[23] is padding
	raw.PayloadLen = binary.LittleEndian.Uint32(data[24:28])

	payloadEnd := 28 + int(raw.PayloadLen)
	if payloadEnd > len(data) {
		payloadEnd = len(data)
	}

	srcIP := uint32ToIP(raw.SrcIP)
	dstIP := uint32ToIP(raw.DstIP)

	// PID/comm are NOT resolved here — this runs on the hot ring buffer
	// reader goroutine. The consumer goroutine fills them in via
	// LookupTCPProcessCached() to avoid blocking the reader.
	return &types.RawPacketEvent{
		TimestampNS: raw.TimestampNS,
		SrcIP:       srcIP,
		DstIP:       dstIP,
		SrcPort:     raw.SrcPort,
		DstPort:     raw.DstPort,
		Direction:   types.Direction(raw.Direction),
		Protocol:    raw.Protocol,
		PID:         0,
		ProcessName: "",
		Payload:     append([]byte(nil), data[28:payloadEnd]...),
	}, nil
}

// attachTC attaches an eBPF program to the TC ingress or egress hook of iface.
func (c *Capturer) attachTC(iface *net.Interface, prog *ebpf.Program, direction string) error {
	ifLink, err := netlink.LinkByName(iface.Name)
	if err != nil {
		return fmt.Errorf("netlink lookup %s: %w", iface.Name, err)
	}

	// Ensure a clsact qdisc exists on the interface.
	qdisc := &netlink.GenericQdisc{
		QdiscAttrs: netlink.QdiscAttrs{
			LinkIndex: ifLink.Attrs().Index,
			Handle:    netlink.MakeHandle(0xffff, 0),
			Parent:    netlink.HANDLE_CLSACT,
		},
		QdiscType: "clsact",
	}
	if err := netlink.QdiscReplace(qdisc); err != nil {
		return fmt.Errorf("create clsact qdisc: %w", err)
	}

	// Determine parent handle for ingress vs egress.
	parent := uint32(netlink.HANDLE_MIN_INGRESS)
	if direction == "egress" {
		parent = netlink.HANDLE_MIN_EGRESS
	}

	// Attach the BPF filter.
	filter := &netlink.BpfFilter{
		FilterAttrs: netlink.FilterAttrs{
			LinkIndex: ifLink.Attrs().Index,
			Parent:    parent,
			Handle:    netlink.MakeHandle(0, 1),
			Protocol:  unix.ETH_P_ALL,
			Priority:  1,
		},
		Fd:           prog.FD(),
		Name:         fmt.Sprintf("traffic-agent-%s", direction),
		DirectAction: true,
	}

	if err := netlink.FilterReplace(filter); err != nil {
		return fmt.Errorf("attach BPF filter (%s): %w", direction, err)
	}

	log.Printf("[capture] attached %s TC filter on %s", direction, iface.Name)
	return nil
}

// ---- Network helpers ----

func uint32ToIP(n uint32) net.IP {
	ip := make(net.IP, 4)
	binary.BigEndian.PutUint32(ip, n)
	return ip
}

func ipToUint32(ip net.IP) uint32 {
	ip4 := ip.To4()
	if ip4 == nil {
		return 0
	}
	return binary.BigEndian.Uint32(ip4)
}
