// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type TCCaptureFilterConfig struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Flags   uint32
}

// LoadTCCapture returns the embedded CollectionSpec for TCCapture.
func LoadTCCapture() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TCCaptureBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TCCapture: %w", err)
	}

	return spec, err
}

// LoadTCCaptureObjects loads TCCapture and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TCCaptureObjects
//	*TCCapturePrograms
//	*TCCaptureMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTCCaptureObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTCCapture()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TCCaptureSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCCaptureSpecs struct {
	TCCaptureProgramSpecs
	TCCaptureMapSpecs
}

// TCCaptureSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCCaptureProgramSpecs struct {
	TcEgress  *ebpf.ProgramSpec `ebpf:"tc_egress"`
	TcIngress *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// TCCaptureMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCCaptureMapSpecs struct {
	Events          *ebpf.MapSpec `ebpf:"events"`
	FilterConfigMap *ebpf.MapSpec `ebpf:"filter_config_map"`
}

// TCCaptureObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTCCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCCaptureObjects struct {
	TCCapturePrograms
	TCCaptureMaps
}

func (o *TCCaptureObjects) Close() error {
	return _TCCaptureClose(
		&o.TCCapturePrograms,
		&o.TCCaptureMaps,
	)
}

// TCCaptureMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTCCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCCaptureMaps struct {
	Events          *ebpf.Map `ebpf:"events"`
	FilterConfigMap *ebpf.Map `ebpf:"filter_config_map"`
}

func (m *TCCaptureMaps) Close() error {
	return _TCCaptureClose(
		m.Events,
		m.FilterConfigMap,
	)
}

// TCCapturePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTCCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCCapturePrograms struct {
	TcEgress  *ebpf.Program `ebpf:"tc_egress"`
	TcIngress *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *TCCapturePrograms) Close() error {
	return _TCCaptureClose(
		p.TcEgress,
		p.TcIngress,
	)
}

func _TCCaptureClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tccapture_bpfel.o
var _TCCaptureBytes []byte
