package tls

import (
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"github.com/traffic-agent/traffic-agent/internal/config"
	"github.com/traffic-agent/traffic-agent/internal/types"
)

// sslDropCount tracks SSL events dropped because the Go channel was full.
var sslDropCount atomic.Uint64

// SSLDropCountReset returns the current SSL drop count and resets it to zero.
func SSLDropCountReset() uint64 {
	return sslDropCount.Swap(0)
}

// maxSSLDataSize must match MAX_SSL_DATA_SIZE in bpf/headers/common.h.
const maxSSLDataSize = 16384

// rawSSLEvent mirrors struct ssl_event from bpf/ssl_uprobe.c.
type rawSSLEvent struct {
	TimestampNS uint64
	ConnID      uint64
	PID         uint32
	TID         uint32
	UID         uint32
	IsRead      uint8
	_           [3]uint8 // padding
	DataLen     uint32
	Comm        [16]byte
	Data        [maxSSLDataSize]byte
}

// Interceptor attaches SSL uprobes to target processes and streams
// captured plaintext to callers via the provided channel.
type Interceptor struct {
	cfg          config.TLSConfig
	objs         SSLUprobeObjects // generated by bpf2go
	links        []link.Link
	reader       *ringbuf.Reader
	mu           sync.Mutex
	attachedLibs map[string]bool // library paths already probed (global)
	scannedPIDs  map[int]bool    // PIDs whose /proc/<pid>/maps has been scanned
	noSSLExes    map[string]bool // exe paths confirmed to have no SSL symbols
	stopScan     chan struct{}
}

// New creates an Interceptor. Call Start to attach probes.
func New(cfg config.TLSConfig) *Interceptor {
	return &Interceptor{
		cfg:          cfg,
		attachedLibs: make(map[string]bool),
		scannedPIDs:  make(map[int]bool),
		noSSLExes:    make(map[string]bool),
		stopScan:     make(chan struct{}),
	}
}

// Start loads eBPF programs and attaches uprobes to all configured targets.
// Events are written to the provided channel.
func (i *Interceptor) Start(events chan<- *types.SSLEvent) error {
	if !i.cfg.Enabled {
		log.Println("[tls] SSL interception disabled")
		return nil
	}

	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}

	if err := LoadSSLUprobeObjects(&i.objs, nil); err != nil {
		return fmt.Errorf("load SSL uprobe eBPF objects: %w", err)
	}

	// Attach to explicitly listed PIDs.
	for _, pid := range i.cfg.PIDs {
		if err := i.attachToPID(pid); err != nil {
			log.Printf("[tls] attach to PID %d: %v", pid, err)
		}
	}

	// Attach to processes matching listed names (scan /proc).
	if len(i.cfg.Processes) > 0 {
		pids, err := findPIDsByName(i.cfg.Processes)
		if err != nil {
			log.Printf("[tls] process scan error: %v", err)
		}
		for _, pid := range pids {
			if err := i.attachToPID(pid); err != nil {
				log.Printf("[tls] attach to PID %d: %v", pid, err)
			}
		}
	}

	// If no specific targets configured, attach globally (PID=0 = all processes).
	if len(i.cfg.PIDs) == 0 && len(i.cfg.Processes) == 0 {
		if err := i.attachGlobal(); err != nil {
			log.Printf("[tls] global attach error: %v", err)
		}
		// Re-scan periodically to pick up new browsers / processes started
		// after the agent (e.g. Firefox opened after agent start).
		go i.periodicScan()
	}

	// Attach BoringSSL uprobes for explicitly configured executables.
	for _, entry := range i.cfg.BoringSSlExecutables {
		if err := i.attachBoringSSlEntry(entry); err != nil {
			log.Printf("[tls] boringssl %q: %v", entry.Path, err)
		}
	}

	var err error
	i.reader, err = ringbuf.NewReader(i.objs.SSLUprobeMaps.SslEvents)
	if err != nil {
		return fmt.Errorf("open SSL ring buffer: %w", err)
	}

	go i.readLoop(events)
	return nil
}

// Stop detaches all uprobes and closes the ring buffer.
func (i *Interceptor) Stop() error {
	// Signal the periodic scanner to exit.
	select {
	case <-i.stopScan: // already closed
	default:
		close(i.stopScan)
	}
	if i.reader != nil {
		_ = i.reader.Close()
	}
	for _, l := range i.links {
		_ = l.Close()
	}
	i.objs.Close()
	return nil
}

// periodicScan re-scans /proc every 10 s and attaches uprobes to any SSL
// library paths not yet covered.  This allows the agent to intercept TLS from
// browsers (Firefox, etc.) that were started after the agent itself.
func (i *Interceptor) periodicScan() {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-i.stopScan:
			return
		case <-ticker.C:
			i.attachGlobal()
		}
	}
}

// AttachToPID dynamically attaches SSL uprobes to a newly-seen PID.
// Safe to call after Start.
func (i *Interceptor) AttachToPID(pid int) error {
	return i.attachToPID(pid)
}

// attachToPID scans all SSL libraries loaded by pid and attaches scoped uprobes.
// It handles OpenSSL, dynamic BoringSSL, GnuTLS, NSS/NSPR, and static BoringSSL
// with ELF symbols — all without requiring per-library configuration.
func (i *Interceptor) attachToPID(pid int) error {
	n := 0
	for _, lib := range findSSLLibsForPID(pid) {
		var err error
		if lib.writeOffset != 0 || lib.readOffset != 0 {
			err = i.attachToLibByOffset(lib, pid)
		} else {
			err = i.attachToLib(lib.path, lib.writeFunc, lib.readFunc, pid, lib.tailCall, lib.isWritev)
		}
		if err != nil {
			log.Printf("[tls] PID %d %s: %v", pid, filepath.Base(lib.path), err)
			continue
		}
		n++
	}
	// Also check the executable itself for static BoringSSL with ELF symbols.
	if exePath, err := os.Readlink(fmt.Sprintf("/proc/%d/exe", pid)); err == nil {
		if wOff, rOff, err := findSSLSymbolOffsets(exePath); err == nil {
			t := &boringSSlTarget{execPath: exePath, sslWriteOffset: wOff, sslReadOffset: rOff, pid: pid}
			if err := i.attachBoringSSlProbes(t); err == nil {
				n++
			}
		}
	}
	if n == 0 {
		return fmt.Errorf("no SSL libraries found for PID %d", pid)
	}
	return nil
}

// attachGlobal scans ALL running processes for any known SSL/TLS shared library
// and attaches system-wide (PID=0) uprobes to each unique library path found.
// It also checks process executables for statically-linked BoringSSL with ELF symbols.
// This covers OpenSSL, dynamic BoringSSL, GnuTLS, and NSS/NSPR automatically —
// no per-library or per-process configuration required.
//
// attachGlobal is idempotent: it skips any paths already in i.attachedLibs so
// it is safe to call repeatedly from the periodic re-scan goroutine.
func (i *Interceptor) attachGlobal() error {
	entries, _ := os.ReadDir("/proc")
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pid, err := strconv.Atoi(e.Name())
		if err != nil {
			continue
		}

		// Skip PIDs we've already scanned — their libraries are either
		// attached or not relevant. This turns the 10s periodic scan from
		// O(all_processes) to O(new_processes), eliminating hundreds of
		// /proc/<pid>/maps reads and ELF parses per cycle.
		i.mu.Lock()
		pidSeen := i.scannedPIDs[pid]
		i.mu.Unlock()
		if pidSeen {
			continue
		}

		// Scan shared libraries loaded by this process.
		for _, lib := range findSSLLibsForPID(pid) {
			// Build a unique attach key per (path, function) combination.
			// Offset-based libs include the offset; symbol-based libs include
			// the write function name so multiple hooks on the same library
			// (e.g. PR_Write + PR_Send on libnspr4.so) are not deduplicated.
			attachKey := lib.path
			if lib.readOffset != 0 {
				attachKey = fmt.Sprintf("%s@read=0x%x", lib.path, lib.readOffset)
			} else if lib.writeFunc != "" {
				attachKey = fmt.Sprintf("%s@%s", lib.path, lib.writeFunc)
			}
			i.mu.Lock()
			seen := i.attachedLibs[attachKey]
			if !seen {
				i.attachedLibs[attachKey] = true
			}
			i.mu.Unlock()
			if seen {
				continue
			}
			var err error
			if lib.writeOffset != 0 || lib.readOffset != 0 {
				err = i.attachToLibByOffset(lib, 0)
			} else {
				err = i.attachToLib(lib.path, lib.writeFunc, lib.readFunc, 0, lib.tailCall, lib.isWritev)
			}
			if err != nil {
				log.Printf("[tls] %s: %v", filepath.Base(lib.path), err)
			}
		}

		// Check the process executable for statically-linked BoringSSL with symbols.
		exePath, err := os.Readlink(fmt.Sprintf("/proc/%d/exe", pid))
		if err != nil {
			i.mu.Lock()
			i.scannedPIDs[pid] = true
			i.mu.Unlock()
			continue
		}
		i.mu.Lock()
		exeAttached := i.attachedLibs[exePath]
		exeNoSSL := i.noSSLExes[exePath]
		i.mu.Unlock()
		if !exeAttached && !exeNoSSL {
			wOff, rOff, err := findSSLSymbolOffsets(exePath)
			if err == nil {
				t := &boringSSlTarget{execPath: exePath, sslWriteOffset: wOff, sslReadOffset: rOff}
				if attachErr := i.attachBoringSSlProbes(t); attachErr == nil {
					i.mu.Lock()
					i.attachedLibs[exePath] = true
					i.mu.Unlock()
				}
			} else {
				// Cache negative result so we don't re-parse this ELF every cycle.
				i.mu.Lock()
				i.noSSLExes[exePath] = true
				i.mu.Unlock()
			}
		}

		i.mu.Lock()
		i.scannedPIDs[pid] = true
		i.mu.Unlock()
	}

	return nil
}

// attachToLibByOffset attaches SSL uprobe programs using file offsets rather
// than symbol names.  Used for stripped binaries where the internal functions
// are not exported (e.g., NSS libssl3.so).
//
// For NSS, only readOffset is set — it points to an internal function that
// fills a buffer with decrypted plaintext during execution.  We attach
// entry+return probes so the data is captured at return time.
//
// writeOffset may be 0 (not available from libssl3.so); outgoing plaintext
// is captured separately via PR_Write on libnspr4.so.
func (i *Interceptor) attachToLibByOffset(lib sslLibFound, pid int) error {
	ex, err := link.OpenExecutable(lib.path)
	if err != nil {
		return fmt.Errorf("open %s: %w", lib.path, err)
	}

	type probeSpec struct {
		prog   *ebpf.Program
		ret    bool
		offset uint64
	}
	var probes []probeSpec

	if lib.writeOffset != 0 {
		probes = append(probes,
			probeSpec{i.objs.UprobeSslWriteEntryCap, false, lib.writeOffset},
		)
	}
	if lib.readOffset != 0 {
		probes = append(probes,
			probeSpec{i.objs.UprobeSslReadEntry, false, lib.readOffset},
			probeSpec{i.objs.UretprobeSslReadRet, true, lib.readOffset},
		)
	}

	for _, p := range probes {
		opts := &link.UprobeOptions{
			PID:     pid,
			Address: p.offset,
		}
		var l link.Link
		if p.ret {
			l, err = ex.Uretprobe("nss_recv_func", p.prog, opts)
		} else {
			l, err = ex.Uprobe("nss_recv_func", p.prog, opts)
		}
		if err != nil {
			return fmt.Errorf("attach NSS uprobe (ret=%v, addr=0x%x): %w", p.ret, p.offset, err)
		}
		i.links = append(i.links, l)
	}

	if pid == 0 {
		log.Printf("[tls] attached NSS read uprobes to %s (recv=0x%x) [entry+return]",
			filepath.Base(lib.path), lib.readOffset)
	} else {
		log.Printf("[tls] attached NSS read uprobes to PID %d via %s (recv=0x%x)",
			pid, filepath.Base(lib.path), lib.readOffset)
	}
	return nil
}

// attachToLib opens path and attaches SSL write/read uprobe programs
// using writeFunc and readFunc as the symbol names.
// pid=0 attaches system-wide; pid>0 scopes the probes to that process only.
//
// tailCall must be set for libraries whose write/read functions are indirect
// tail-calls (br x3 on ARM64) rather than normal functions with a RET.
// In that case uretprobes will never fire, so the agent uses an entry-only
// write capture program and skips read probes entirely.
// NSS/NSPR (libnspr4.so) is the canonical example.
//
// isWritev must be set for scatter-gather write functions (PR_Writev) that
// take an iov array instead of a direct buffer pointer.
func (i *Interceptor) attachToLib(path, writeFunc, readFunc string, pid int, tailCall, isWritev bool) error {
	ex, err := link.OpenExecutable(path)
	if err != nil {
		return fmt.Errorf("open %s: %w", path, err)
	}

	type probeSpec struct {
		sym  string
		prog *ebpf.Program
		ret  bool
	}
	var probes []probeSpec
	if tailCall {
		// PR_Write / PR_Read are 3-instruction tail-calls on ARM64.
		// Only attach an entry-only write probe; reads are not interceptable
		// without private NSS symbol access.
		prog := i.objs.UprobeSslWriteEntryCap
		if isWritev {
			prog = i.objs.UprobeSslWritevEntryCap
		}
		probes = []probeSpec{
			{writeFunc, prog, false},
		}
	} else {
		probes = []probeSpec{
			{writeFunc, i.objs.UprobeSslWriteEntry, false},
			{writeFunc, i.objs.UretprobeSslWriteRet, true},
			{readFunc, i.objs.UprobeSslReadEntry, false},
			{readFunc, i.objs.UretprobeSslReadRet, true},
		}
	}

	var opts *link.UprobeOptions
	if pid != 0 {
		opts = &link.UprobeOptions{PID: pid}
	}
	for _, p := range probes {
		var l link.Link
		if p.ret {
			l, err = ex.Uretprobe(p.sym, p.prog, opts)
		} else {
			l, err = ex.Uprobe(p.sym, p.prog, opts)
		}
		if err != nil {
			return fmt.Errorf("uprobe %s: %w", p.sym, err)
		}
		i.links = append(i.links, l)
	}

	mode := "entry+return"
	if tailCall {
		mode = "entry-only (tail-call)"
	}
	if pid == 0 {
		log.Printf("[tls] attached global uprobes to %s (%s/%s) [%s]",
			filepath.Base(path), writeFunc, readFunc, mode)
	} else {
		log.Printf("[tls] attached uprobes to PID %d via %s (%s/%s) [%s]",
			pid, filepath.Base(path), writeFunc, readFunc, mode)
	}
	return nil
}

// ---- BoringSSL attachment methods ----

// attachBoringSSlEntry processes one BoringSSlExecutable config entry.
// It resolves the target binary, resolves SSL offsets (or uses config-provided
// ones), and attaches uprobes — scoped per-PID if process_name is set,
// or system-wide otherwise.
func (i *Interceptor) attachBoringSSlEntry(entry config.BoringSSlExecutable) error {
	dynamic := isDynamicLib(entry.Path)

	if entry.ProcessName != "" {
		// Find all running PIDs matching the process name.
		pids, err := findPIDsByName([]string{entry.ProcessName})
		if err != nil {
			return fmt.Errorf("find pids: %w", err)
		}
		if len(pids) == 0 {
			log.Printf("[tls] boringssl: no running processes named %q (will miss if started later)", entry.ProcessName)
			return nil
		}
		seen := make(map[string]bool)
		for _, pid := range pids {
			exePath := resolveExecPath(entry.Path, pid)
			writeOff, readOff := entry.SSLWriteOffset, entry.SSLReadOffset
			if !dynamic && writeOff == 0 {
				writeOff, readOff, _ = findSSLSymbolOffsets(exePath)
			}
			t := &boringSSlTarget{
				execPath:       exePath,
				sslWriteOffset: writeOff,
				sslReadOffset:  readOff,
				isDynamic:      dynamic,
				pid:            pid,
			}
			// For static binaries, avoid attaching the same on-disk file twice
			// (multiple processes share the same inode; one system-wide attach suffices).
			if !dynamic {
				if seen[exePath] {
					continue
				}
				t.pid = 0 // attach system-wide for static binary
				seen[exePath] = true
			}
			if err := i.attachBoringSSlProbes(t); err != nil {
				log.Printf("[tls] boringssl attach %s (pid=%d): %v", exePath, t.pid, err)
			}
		}
		return nil
	}

	// No process_name: attach system-wide.
	realPath := resolveExecPath(entry.Path, 0)
	writeOff, readOff := entry.SSLWriteOffset, entry.SSLReadOffset
	if !dynamic && writeOff == 0 {
		writeOff, readOff, _ = findSSLSymbolOffsets(realPath)
	}
	t := &boringSSlTarget{
		execPath:       realPath,
		sslWriteOffset: writeOff,
		sslReadOffset:  readOff,
		isDynamic:      dynamic,
		pid:            0,
	}
	return i.attachBoringSSlProbes(t)
}

// attachBoringSSlProbes attaches the four SSL uprobe/uretprobe programs to t.
// For dynamic libraries or binaries with symbol tables (t.sslWriteOffset == 0),
// it uses symbol-name lookup. For stripped static binaries it uses the file
// offsets in t.sslWriteOffset / t.sslReadOffset via UprobeOptions.Address,
// which bypasses cilium/ebpf's internal symbol resolution entirely.
func (i *Interceptor) attachBoringSSlProbes(t *boringSSlTarget) error {
	if !t.isDynamic && t.sslWriteOffset == 0 {
		return fmt.Errorf(
			"no SSL symbols found and no offsets configured for %s — "+
				"set ssl_write_offset and ssl_read_offset in boringssl_executables config",
			t.execPath,
		)
	}

	ex, err := link.OpenExecutable(t.execPath)
	if err != nil {
		return fmt.Errorf("open executable %s: %w", t.execPath, err)
	}

	type probeSpec struct {
		sym    string
		prog   *ebpf.Program
		ret    bool
		offset uint64
	}
	probes := []probeSpec{
		{"SSL_write", i.objs.UprobeSslWriteEntry, false, t.sslWriteOffset},
		{"SSL_write", i.objs.UretprobeSslWriteRet, true, t.sslWriteOffset},
		{"SSL_read", i.objs.UprobeSslReadEntry, false, t.sslReadOffset},
		{"SSL_read", i.objs.UretprobeSslReadRet, true, t.sslReadOffset},
	}

	for _, p := range probes {
		opts := &link.UprobeOptions{PID: t.pid}
		if !t.isDynamic && p.offset > 0 {
			// Offset-based attachment: bypasses symbol lookup for stripped binaries.
			opts.Address = p.offset
		}
		var l link.Link
		if p.ret {
			l, err = ex.Uretprobe(p.sym, p.prog, opts)
		} else {
			l, err = ex.Uprobe(p.sym, p.prog, opts)
		}
		if err != nil {
			return fmt.Errorf("attach uprobe %s (ret=%v, addr=0x%x): %w", p.sym, p.ret, p.offset, err)
		}
		i.links = append(i.links, l)
	}

	log.Printf("[tls] attached BoringSSL uprobes to %s (pid=%d, dynamic=%v, write_off=0x%x)",
		filepath.Base(t.execPath), t.pid, t.isDynamic, t.sslWriteOffset)
	return nil
}

// readLoop reads SSL events from the ring buffer and forwards them.
func (i *Interceptor) readLoop(ch chan<- *types.SSLEvent) {
	for {
		record, err := i.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			log.Printf("[tls] ring buffer read error: %v", err)
			continue
		}

		ev, err := parseSSLEvent(record.RawSample)
		if err != nil {
			log.Printf("[tls] parse error: %v", err)
			continue
		}

		select {
		case ch <- ev:
		default:
			sslDropCount.Add(1)
		}
	}
}

func parseSSLEvent(data []byte) (*types.SSLEvent, error) {
	// The fixed header is 52 bytes (before the variable-length data field).
	// Layout: timestamp_ns(8) + conn_id(8) + pid(4) + tid(4) + uid(4) +
	//         is_read(1) + pad(3) + data_len(4) + comm(16) = 52
	const headerSize = 52
	if len(data) < headerSize {
		return nil, fmt.Errorf("short SSL record: %d bytes", len(data))
	}

	var raw rawSSLEvent
	raw.TimestampNS = binary.LittleEndian.Uint64(data[0:8])
	raw.ConnID = binary.LittleEndian.Uint64(data[8:16])
	raw.PID = binary.LittleEndian.Uint32(data[16:20])
	raw.TID = binary.LittleEndian.Uint32(data[20:24])
	raw.UID = binary.LittleEndian.Uint32(data[24:28])
	raw.IsRead = data[28]
	raw.DataLen = binary.LittleEndian.Uint32(data[32:36])
	copy(raw.Comm[:], data[36:52])

	dataStart := 52
	dataEnd := dataStart + int(raw.DataLen)
	if dataEnd > len(data) {
		dataEnd = len(data)
	}

	comm := strings.TrimRight(string(raw.Comm[:]), "\x00")
	return &types.SSLEvent{
		TimestampNS: raw.TimestampNS,
		ConnID:      raw.ConnID,
		PID:         raw.PID,
		TID:         raw.TID,
		UID:         raw.UID,
		IsRead:      raw.IsRead != 0,
		ProcessName: comm,
		Data:        append([]byte(nil), data[dataStart:dataEnd]...),
	}, nil
}

// ---- Process discovery helpers ----

// findPIDsByName returns PIDs of all processes whose comm matches any name in names.
func findPIDsByName(names []string) ([]int, error) {
	nameSet := make(map[string]struct{}, len(names))
	for _, n := range names {
		nameSet[n] = struct{}{}
	}

	entries, err := os.ReadDir("/proc")
	if err != nil {
		return nil, fmt.Errorf("read /proc: %w", err)
	}

	var pids []int
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pid, err := strconv.Atoi(e.Name())
		if err != nil {
			continue
		}

		commPath := filepath.Join("/proc", e.Name(), "comm")
		commBytes, err := os.ReadFile(commPath)
		if err != nil {
			continue
		}
		comm := strings.TrimSpace(string(commBytes))

		if _, ok := nameSet[comm]; ok {
			pids = append(pids, pid)
		}
	}
	return pids, nil
}

