package tls

import (
	"bufio"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"github.com/traffic-agent/traffic-agent/internal/config"
	"github.com/traffic-agent/traffic-agent/internal/types"
)

const maxSSLDataSize = 4096

// rawSSLEvent mirrors struct ssl_event from bpf/ssl_uprobe.c.
type rawSSLEvent struct {
	TimestampNS uint64
	PID         uint32
	TID         uint32
	UID         uint32
	IsRead      uint8
	_           [3]uint8 // padding
	DataLen     uint32
	Comm        [16]byte
	Data        [maxSSLDataSize]byte
}

// Interceptor attaches SSL uprobes to target processes and streams
// captured plaintext to callers via the provided channel.
type Interceptor struct {
	cfg    config.TLSConfig
	objs   SSLUprobeObjects // generated by bpf2go
	links  []link.Link
	reader *ringbuf.Reader
}

// New creates an Interceptor. Call Start to attach probes.
func New(cfg config.TLSConfig) *Interceptor {
	return &Interceptor{cfg: cfg}
}

// Start loads eBPF programs and attaches uprobes to all configured targets.
// Events are written to the provided channel.
func (i *Interceptor) Start(events chan<- *types.SSLEvent) error {
	if !i.cfg.Enabled {
		log.Println("[tls] SSL interception disabled")
		return nil
	}

	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}

	if err := LoadSSLUprobeObjects(&i.objs, nil); err != nil {
		return fmt.Errorf("load SSL uprobe eBPF objects: %w", err)
	}

	// Attach to explicitly listed PIDs.
	for _, pid := range i.cfg.PIDs {
		if err := i.attachToPID(pid); err != nil {
			log.Printf("[tls] attach to PID %d: %v", pid, err)
		}
	}

	// Attach to processes matching listed names (scan /proc).
	if len(i.cfg.Processes) > 0 {
		pids, err := findPIDsByName(i.cfg.Processes)
		if err != nil {
			log.Printf("[tls] process scan error: %v", err)
		}
		for _, pid := range pids {
			if err := i.attachToPID(pid); err != nil {
				log.Printf("[tls] attach to PID %d: %v", pid, err)
			}
		}
	}

	var err error
	i.reader, err = ringbuf.NewReader(i.objs.SSLUprobeMaps.SslEvents)
	if err != nil {
		return fmt.Errorf("open SSL ring buffer: %w", err)
	}

	go i.readLoop(events)
	return nil
}

// Stop detaches all uprobes and closes the ring buffer.
func (i *Interceptor) Stop() error {
	if i.reader != nil {
		_ = i.reader.Close()
	}
	for _, l := range i.links {
		_ = l.Close()
	}
	i.objs.Close()
	return nil
}

// AttachToPID dynamically attaches SSL uprobes to a newly-seen PID.
// Safe to call after Start.
func (i *Interceptor) AttachToPID(pid int) error {
	return i.attachToPID(pid)
}

// attachToPID finds libssl.so in the PID's memory map and attaches uprobes.
func (i *Interceptor) attachToPID(pid int) error {
	libPath, err := findLibSSL(pid, i.cfg.LibSSLPath)
	if err != nil {
		return fmt.Errorf("find libssl for PID %d: %w", pid, err)
	}

	ex, err := link.OpenExecutable(libPath)
	if err != nil {
		return fmt.Errorf("open executable %s: %w", libPath, err)
	}

	probes := []struct {
		sym  string
		prog *ebpf.Program
		ret  bool
	}{
		{"SSL_write", i.objs.UprobeSslWriteEntry, false},
		{"SSL_write", i.objs.UretprobeSslWriteRet, true},
		{"SSL_read", i.objs.UprobeSslReadEntry, false},
		{"SSL_read", i.objs.UretprobeSslReadRet, true},
	}

	for _, p := range probes {
		var l link.Link
		var err error

		opts := &link.UprobeOptions{PID: pid}
		if p.ret {
			l, err = ex.Uretprobe(p.sym, p.prog, opts)
		} else {
			l, err = ex.Uprobe(p.sym, p.prog, opts)
		}
		if err != nil {
			return fmt.Errorf("attach uprobe %s (ret=%v): %w", p.sym, p.ret, err)
		}
		i.links = append(i.links, l)
	}

	log.Printf("[tls] attached SSL uprobes to PID %d (%s)", pid, libPath)
	return nil
}

// readLoop reads SSL events from the ring buffer and forwards them.
func (i *Interceptor) readLoop(ch chan<- *types.SSLEvent) {
	for {
		record, err := i.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			log.Printf("[tls] ring buffer read error: %v", err)
			continue
		}

		ev, err := parseSSLEvent(record.RawSample)
		if err != nil {
			log.Printf("[tls] parse error: %v", err)
			continue
		}

		select {
		case ch <- ev:
		default:
			log.Printf("[tls] dropping SSL event: channel full")
		}
	}
}

func parseSSLEvent(data []byte) (*types.SSLEvent, error) {
	minSize := int(unsafe.Sizeof(rawSSLEvent{}))
	if len(data) < minSize {
		return nil, fmt.Errorf("short SSL record: %d bytes", len(data))
	}

	var raw rawSSLEvent
	raw.TimestampNS = binary.LittleEndian.Uint64(data[0:8])
	raw.PID = binary.LittleEndian.Uint32(data[8:12])
	raw.TID = binary.LittleEndian.Uint32(data[12:16])
	raw.UID = binary.LittleEndian.Uint32(data[16:20])
	raw.IsRead = data[20]
	raw.DataLen = binary.LittleEndian.Uint32(data[24:28])
	copy(raw.Comm[:], data[28:44])

	dataStart := 44
	dataEnd := dataStart + int(raw.DataLen)
	if dataEnd > len(data) {
		dataEnd = len(data)
	}

	comm := strings.TrimRight(string(raw.Comm[:]), "\x00")
	return &types.SSLEvent{
		TimestampNS: raw.TimestampNS,
		PID:         raw.PID,
		TID:         raw.TID,
		UID:         raw.UID,
		IsRead:      raw.IsRead != 0,
		ProcessName: comm,
		Data:        append([]byte(nil), data[dataStart:dataEnd]...),
	}, nil
}

// ---- Process discovery helpers ----

// findLibSSL returns the path to libssl.so for a given PID.
// If explicitPath is non-empty, it is returned directly.
func findLibSSL(pid int, explicitPath string) (string, error) {
	if explicitPath != "" {
		return explicitPath, nil
	}

	mapsPath := fmt.Sprintf("/proc/%d/maps", pid)
	f, err := os.Open(mapsPath)
	if err != nil {
		return "", fmt.Errorf("open %s: %w", mapsPath, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		// Each line: address perms offset dev inode pathname
		// e.g.: 7f1234 r-xp 0000 fd:01 12345 /lib/x86_64-linux-gnu/libssl.so.3
		if strings.Contains(line, "libssl.so") {
			fields := strings.Fields(line)
			if len(fields) >= 6 {
				return fields[5], nil
			}
		}
	}
	return "", fmt.Errorf("libssl.so not found in /proc/%d/maps", pid)
}

// findPIDsByName returns PIDs of all processes whose comm matches any name in names.
func findPIDsByName(names []string) ([]int, error) {
	nameSet := make(map[string]struct{}, len(names))
	for _, n := range names {
		nameSet[n] = struct{}{}
	}

	entries, err := os.ReadDir("/proc")
	if err != nil {
		return nil, fmt.Errorf("read /proc: %w", err)
	}

	var pids []int
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pid, err := strconv.Atoi(e.Name())
		if err != nil {
			continue
		}

		commPath := filepath.Join("/proc", e.Name(), "comm")
		commBytes, err := os.ReadFile(commPath)
		if err != nil {
			continue
		}
		comm := strings.TrimSpace(string(commBytes))

		if _, ok := nameSet[comm]; ok {
			pids = append(pids, pid)
		}
	}
	return pids, nil
}

