// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package tls

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SSLUprobeQuicHkdfArgs struct {
	LabelPtr  uint64
	OutputPtr uint64
	LabelLen  uint32
	OutputLen uint32
	HashType  uint32
	Variant   uint32
}

type SSLUprobeSslArgs struct {
	Buf    uint64
	ConnId uint64
	Num    uint32
	Pad    uint32
}

// LoadSSLUprobe returns the embedded CollectionSpec for SSLUprobe.
func LoadSSLUprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SSLUprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SSLUprobe: %w", err)
	}

	return spec, err
}

// LoadSSLUprobeObjects loads SSLUprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SSLUprobeObjects
//	*SSLUprobePrograms
//	*SSLUprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSSLUprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSSLUprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SSLUprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SSLUprobeSpecs struct {
	SSLUprobeProgramSpecs
	SSLUprobeMapSpecs
}

// SSLUprobeSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SSLUprobeProgramSpecs struct {
	UprobeQuicHkdfExpandEntry  *ebpf.ProgramSpec `ebpf:"uprobe_quic_hkdf_expand_entry"`
	UprobeSslReadEntry         *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadEntryNspr     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry_nspr"`
	UprobeSslWriteEntry        *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteEntryCap     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_entry_cap"`
	UprobeSslWritevEntryCap    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_writev_entry_cap"`
	UretprobeQuicHkdfExpandRet *ebpf.ProgramSpec `ebpf:"uretprobe_quic_hkdf_expand_ret"`
	UretprobeSslReadRet        *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ret"`
	UretprobeSslWriteRet       *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write_ret"`
}

// SSLUprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SSLUprobeMapSpecs struct {
	ActiveQuicHkdfArgs *ebpf.MapSpec `ebpf:"active_quic_hkdf_args"`
	ActiveSslReadArgs  *ebpf.MapSpec `ebpf:"active_ssl_read_args"`
	ActiveSslWriteArgs *ebpf.MapSpec `ebpf:"active_ssl_write_args"`
	QuicKeyEvents      *ebpf.MapSpec `ebpf:"quic_key_events"`
	SslEvents          *ebpf.MapSpec `ebpf:"ssl_events"`
}

// SSLUprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSSLUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type SSLUprobeObjects struct {
	SSLUprobePrograms
	SSLUprobeMaps
}

func (o *SSLUprobeObjects) Close() error {
	return _SSLUprobeClose(
		&o.SSLUprobePrograms,
		&o.SSLUprobeMaps,
	)
}

// SSLUprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSSLUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type SSLUprobeMaps struct {
	ActiveQuicHkdfArgs *ebpf.Map `ebpf:"active_quic_hkdf_args"`
	ActiveSslReadArgs  *ebpf.Map `ebpf:"active_ssl_read_args"`
	ActiveSslWriteArgs *ebpf.Map `ebpf:"active_ssl_write_args"`
	QuicKeyEvents      *ebpf.Map `ebpf:"quic_key_events"`
	SslEvents          *ebpf.Map `ebpf:"ssl_events"`
}

func (m *SSLUprobeMaps) Close() error {
	return _SSLUprobeClose(
		m.ActiveQuicHkdfArgs,
		m.ActiveSslReadArgs,
		m.ActiveSslWriteArgs,
		m.QuicKeyEvents,
		m.SslEvents,
	)
}

// SSLUprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSSLUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type SSLUprobePrograms struct {
	UprobeQuicHkdfExpandEntry  *ebpf.Program `ebpf:"uprobe_quic_hkdf_expand_entry"`
	UprobeSslReadEntry         *ebpf.Program `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadEntryNspr     *ebpf.Program `ebpf:"uprobe_ssl_read_entry_nspr"`
	UprobeSslWriteEntry        *ebpf.Program `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteEntryCap     *ebpf.Program `ebpf:"uprobe_ssl_write_entry_cap"`
	UprobeSslWritevEntryCap    *ebpf.Program `ebpf:"uprobe_ssl_writev_entry_cap"`
	UretprobeQuicHkdfExpandRet *ebpf.Program `ebpf:"uretprobe_quic_hkdf_expand_ret"`
	UretprobeSslReadRet        *ebpf.Program `ebpf:"uretprobe_ssl_read_ret"`
	UretprobeSslWriteRet       *ebpf.Program `ebpf:"uretprobe_ssl_write_ret"`
}

func (p *SSLUprobePrograms) Close() error {
	return _SSLUprobeClose(
		p.UprobeQuicHkdfExpandEntry,
		p.UprobeSslReadEntry,
		p.UprobeSslReadEntryNspr,
		p.UprobeSslWriteEntry,
		p.UprobeSslWriteEntryCap,
		p.UprobeSslWritevEntryCap,
		p.UretprobeQuicHkdfExpandRet,
		p.UretprobeSslReadRet,
		p.UretprobeSslWriteRet,
	)
}

func _SSLUprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ssluprobe_bpfel.o
var _SSLUprobeBytes []byte
